apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: myclusters.thesis.io
spec:
  group: thesis.io
  names:
    kind: myCluster
    plural: myclusters
  connectionSecretKeys:
    - cluster-ca
    - apiserver-endpoint
    - value
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                providerConfigRef:
                  description: Name of provider
                  type: string

                k8s-version:
                  description: Kubernetes version
                  type: string
                  enum: ["1.20", "1.21", "1.22", "1.23", "1.24"]
                workers-size:
                  description: Desired number of worker nodes in the cluster
                  type: integer
                  default: 2
                workload-type:
                  description: Type of workloads to be run on this cluster (GPU or non-GPU)"
                  type: string
                  enum: ["gpu", "non-gpu"]
                  default: "non-gpu"
                region:
                  description: Geographic location of this Cluster Setup
                  type: string
                  enum: ["eu-central-1", "eu-west-1"]


                vpc-cidrBlock:
                  description: CIDR block for VPC
                  type: string
                  default: "10.19.0.0/16"

                public-subnet-name:
                  description: Name for public subnet
                  type: string
                  default: "public"
                public-subnet-cidrBlock:
                  description: CIDR block for public subnet
                  type: string
                  default: "10.19.0.0/24"
                public-subnet-availabilityZone:
                  description: AZ for public subnet
                  type: string
                  enum: ["a", "b", "c"]
                  default: "a"

                private-subnet-1-name:
                  description: Name for private subnet 1
                  type: string
                  default: "private-1"
                private-subnet-1-cidrBlock:
                  description: CIDR block for private subnet 1
                  type: string
                  default: "10.19.1.0/24"
                private-subnet-1-availabilityZone:
                  description: AZ for private subnet 1
                  type: string
                  enum: [ "a", "b", "c" ]
                  default: "a"

                private-subnet-2-name:
                  description: Name for private subnet 2
                  type: string
                  default: "private-2"
                private-subnet-2-cidrBlock:
                  description: CIDR block for private subnet 2
                  type: string
                  default: "10.19.2.0/24"
                private-subnet-2-availabilityZone:
                  description: AZ for private subnet 2
                  type: string
                  enum: [ "a", "b", "c" ]
                  default: "b"

              required:
                    - region
                    - k8s-version
                    - provider-config-ref