resources:
  - ../../base
namePrefix: dev-
patches:
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: IDENTIFIER
          value: "TEAM_2_DEV"
    target:
      kind: Deployment