apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clustertools
spec:
  generators:
    - git:
        repoURL: https://github.com/crimbler2/argocd-infrastructure-repo.git
        revision: HEAD
        directories:
          - path: clustertools/*
  template:
    metadata:
      name: '{{path.basenameNormalized}}-app-of-apps'
    spec:
      project: default
      source:
        repoURL: https://github.com/crimbler2/argocd-infrastructure-repo.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basenameNormalized}}-system'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    # Set Application finalizer
    preserveResourcesOnDeletion: false