apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  generators:
    - git:
        repoURL: https://github.com/crimbler2/argocd-infrastructure-repo.git
        revision: HEAD
        files:
          - path: tenants/*-config.yaml

  template:
    metadata:
      name: '{{tenant.name}}-app-of-apps'
    spec:
      project: default
      source:
        repoURL: '{{repository.url}}'
        targetRevision: HEAD
        path: '{{repository.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{tenant.namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true

  syncPolicy:
    # Set Application finalizer
    preserveResourcesOnDeletion: false