apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sample
  namespace: apps
spec:
  project: default

  source:
    repoURL: https://github.com/crimbler2/argocd-infrastructure-repo
    targetRevision: HEAD
    path: remote_repo_team_1/nginx-sample/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
