apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-chart
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
