---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-helm-repo
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: crossplane
  url: https://charts.crossplane.io/stable
  type: helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-chart
  namespace: argocd-system
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.1
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
