---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-helm-repo
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: external-secrets
  url: https://charts.external-secrets.io
  type: helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-chart
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---

