# Wait for installation of providers so their respective ProviderConfig resources are available
apiVersion: batch/v1
kind: Job
metadata:
  generateName: after-providers
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-70"
spec:
  template:
    spec:
      containers:
        - name: page-down
          image: alpine:latest
          command: ["sleep", "10"]
      restartPolicy: Never