---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-helm-repo
  namespace: argocd-system
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
stringData:
  name: crossplane
  url: https://charts.crossplane.io/stable
  type: helm
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-chart
  namespace: argocd-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.10.1
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---

