apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: helm-provider
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-80"
spec:
  package: crossplane/provider-helm:v0.11.1