apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-provider-sa
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-92"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-provider-permissions
  annotations:
    argocd.argoproj.io/sync-wave: "-91"
subjects:
  - kind: ServiceAccount
    name: kubernetes-provider-sa
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: kubernetes-controller-config
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-90"
spec:
  serviceAccountName: kubernetes-provider-sa
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: kubernetes-provider
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-80"
spec:
  package: crossplane/provider-kubernetes:v0.4.1
  controllerConfigRef:
    name: kubernetes-controller-config
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-60"
spec:
  credentials:
    source: InjectedIdentity